export default class locationInfo{
  name:string
  id:string
  lat:string
  lon:string
  adm2:string
  adm1:string
  country:string
  tz:string
  utcOffset:string
  isDst:string
  type:string
  rank:string
  fxLink:string

  constructor() {
    this.name=''
    this.id=''
    this.lat=''
    this.lon=''
    this.adm2=''
    this.adm1=''
    this.country=''
    this.tz=''
    this.utcOffset=''
    this.isDst=''
    this.type=''
    this.rank=''
    this.fxLink=''
  }

}