export default class weatherInfo7{
  fxDate: string
  sunrise: string
  sunset: string
  moonrise: string
  moonset: string
  moonPhase: string
  moonPhaseIcon: string
  tempMax: string
  tempMin: string
  iconDay: string
  textDay: string
  iconNight: string
  textNight: string
  wind360Day: string
  windDirDay: string
  windScaleDay: string
  windSpeedDay: string
  wind360Night: string
  windDirNight: string
  windScaleNight: string
  windSpeedNight: string
  humidity: string
  precip: string
  pressure: string
  vis: string
  cloud: string
  uvIndex: string

  constructor() {
    this.fxDate=''
    this.sunrise=''
    this.sunset=''
    this.moonrise=''
    this.moonset=''
    this.moonPhase=''
    this.moonPhaseIcon=''
    this.tempMax=''
    this.tempMin=''
    this.iconDay=''
    this.textDay=''
    this.iconNight=''
    this.textNight=''
    this.wind360Day=''
    this.windDirDay=''
    this.windScaleDay=''
    this.windSpeedDay=''
    this.wind360Night=''
    this.windDirNight=''
    this.windScaleNight=''
    this.windSpeedNight=''
    this.humidity=''
    this.precip=''
    this.pressure=''
    this.vis=''
    this.cloud=''
    this.uvIndex=''
  }
}